# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vitor/aulas/Project_Final/Video_DoorBell_Code/Video_DoorBell_Code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vitor/aulas/Project_Final/Video_DoorBell_Code/Video_DoorBell_Code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vitor/aulas/Project_Final/Video_DoorBell_Code/Video_DoorBell_Code/CMakeFiles /home/vitor/aulas/Project_Final/Video_DoorBell_Code/Video_DoorBell_Code//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vitor/aulas/Project_Final/Video_DoorBell_Code/Video_DoorBell_Code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mainlocal.elf

# Build rule for target.
mainlocal.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mainlocal.elf
.PHONY : mainlocal.elf

# fast build rule for target.
mainlocal.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/build
.PHONY : mainlocal.elf/fast

mainlocal.o: mainlocal.cpp.o
.PHONY : mainlocal.o

# target to build an object file
mainlocal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/mainlocal.cpp.o
.PHONY : mainlocal.cpp.o

mainlocal.i: mainlocal.cpp.i
.PHONY : mainlocal.i

# target to preprocess a source file
mainlocal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/mainlocal.cpp.i
.PHONY : mainlocal.cpp.i

mainlocal.s: mainlocal.cpp.s
.PHONY : mainlocal.s

# target to generate assembly for a file
mainlocal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/mainlocal.cpp.s
.PHONY : mainlocal.cpp.s

src/CCamera.o: src/CCamera.cpp.o
.PHONY : src/CCamera.o

# target to build an object file
src/CCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CCamera.cpp.o
.PHONY : src/CCamera.cpp.o

src/CCamera.i: src/CCamera.cpp.i
.PHONY : src/CCamera.i

# target to preprocess a source file
src/CCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CCamera.cpp.i
.PHONY : src/CCamera.cpp.i

src/CCamera.s: src/CCamera.cpp.s
.PHONY : src/CCamera.s

# target to generate assembly for a file
src/CCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CCamera.cpp.s
.PHONY : src/CCamera.cpp.s

src/CDatabase.o: src/CDatabase.cpp.o
.PHONY : src/CDatabase.o

# target to build an object file
src/CDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CDatabase.cpp.o
.PHONY : src/CDatabase.cpp.o

src/CDatabase.i: src/CDatabase.cpp.i
.PHONY : src/CDatabase.i

# target to preprocess a source file
src/CDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CDatabase.cpp.i
.PHONY : src/CDatabase.cpp.i

src/CDatabase.s: src/CDatabase.cpp.s
.PHONY : src/CDatabase.s

# target to generate assembly for a file
src/CDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CDatabase.cpp.s
.PHONY : src/CDatabase.cpp.s

src/CLivestream.o: src/CLivestream.cpp.o
.PHONY : src/CLivestream.o

# target to build an object file
src/CLivestream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CLivestream.cpp.o
.PHONY : src/CLivestream.cpp.o

src/CLivestream.i: src/CLivestream.cpp.i
.PHONY : src/CLivestream.i

# target to preprocess a source file
src/CLivestream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CLivestream.cpp.i
.PHONY : src/CLivestream.cpp.i

src/CLivestream.s: src/CLivestream.cpp.s
.PHONY : src/CLivestream.s

# target to generate assembly for a file
src/CLivestream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CLivestream.cpp.s
.PHONY : src/CLivestream.cpp.s

src/CLocalS.o: src/CLocalS.cpp.o
.PHONY : src/CLocalS.o

# target to build an object file
src/CLocalS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CLocalS.cpp.o
.PHONY : src/CLocalS.cpp.o

src/CLocalS.i: src/CLocalS.cpp.i
.PHONY : src/CLocalS.i

# target to preprocess a source file
src/CLocalS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CLocalS.cpp.i
.PHONY : src/CLocalS.cpp.i

src/CLocalS.s: src/CLocalS.cpp.s
.PHONY : src/CLocalS.s

# target to generate assembly for a file
src/CLocalS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainlocal.elf.dir/build.make CMakeFiles/mainlocal.elf.dir/src/CLocalS.cpp.s
.PHONY : src/CLocalS.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mainlocal.elf"
	@echo "... mainlocal.o"
	@echo "... mainlocal.i"
	@echo "... mainlocal.s"
	@echo "... src/CCamera.o"
	@echo "... src/CCamera.i"
	@echo "... src/CCamera.s"
	@echo "... src/CDatabase.o"
	@echo "... src/CDatabase.i"
	@echo "... src/CDatabase.s"
	@echo "... src/CLivestream.o"
	@echo "... src/CLivestream.i"
	@echo "... src/CLivestream.s"
	@echo "... src/CLocalS.o"
	@echo "... src/CLocalS.i"
	@echo "... src/CLocalS.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

